const NORMS={
'ISO 31000':{m:'security',fn:'ISO 31000:2018 – Risikomanagement',reqs:[{n:'5.2',t:'Führung und Verpflichtung'},{n:'6.3',t:'Risikoidentifikation'},{n:'6.4',t:'Risikoanalyse'},{n:'6.5',t:'Risikobewertung'},{n:'6.6',t:'Risikobehandlung'},{n:'6.7',t:'Überwachung'}]},
'ISO/IEC 27001':{m:'security',fn:'ISO/IEC 27001:2022 – Informationssicherheit',reqs:[{n:'A.5',t:'Informationssicherheitsrichtlinien'},{n:'A.7',t:'Personalsicherheit'},{n:'A.8',t:'Asset Management'},{n:'A.9',t:'Zugangssteuerung'},{n:'A.11',t:'Physische Sicherheit'},{n:'A.12',t:'Betriebssicherheit'},{n:'A.15',t:'Lieferantenbeziehungen'},{n:'A.16',t:'Vorfallmanagement'},{n:'A.17',t:'BCM'},{n:'A.18',t:'Compliance'}]},
'ISO 22301':{m:'security',fn:'ISO 22301:2019 – Business Continuity',reqs:[{n:'8.2',t:'Business Impact Analyse'},{n:'8.3',t:'BC-Strategien'},{n:'8.4',t:'BC-Pläne'},{n:'8.5',t:'Übungsprogramm'},{n:'9',t:'Leistungsbewertung'}]},
'BSI IT-Grundschutz':{m:'security',fn:'BSI IT-Grundschutz-Kompendium',reqs:[{n:'ISMS.1',t:'Sicherheitsmanagement'},{n:'ORP.1',t:'Organisation'},{n:'ORP.3',t:'Schulung'},{n:'CON.3',t:'Datensicherung'},{n:'DER.1',t:'Detektion'},{n:'INF.1',t:'Gebäude'},{n:'INF.2',t:'Rechenzentrum'}]},
'KRITIS-DachG':{m:'security',fn:'KRITIS-Dachgesetz',reqs:[{n:'§13',t:'Resilienzmaßnahmen'},{n:'§14',t:'Risikoanalyse'},{n:'§15',t:'Meldepflichten'},{n:'§16',t:'Personalüberprüfung'}]},
'NIS2':{m:'security',fn:'NIS2-Umsetzungsgesetz',reqs:[{n:'§30',t:'Risikomanagement'},{n:'§31',t:'Meldepflicht'},{n:'§38',t:'Schulungspflicht GF'}]},
'ISO 9001':{m:'qm',fn:'ISO 9001:2015 – Qualitätsmanagement',reqs:[{n:'4.1',t:'Kontext'},{n:'4.2',t:'Interessierte Parteien'},{n:'5.2',t:'Qualitätspolitik'},{n:'6.1',t:'Risiken & Chancen'},{n:'6.2',t:'Qualitätsziele'},{n:'7.2',t:'Kompetenz'},{n:'7.5',t:'Dokumentation'},{n:'8.2',t:'Kundenanforderungen'},{n:'8.4',t:'Externe Anbieter'},{n:'8.7',t:'Nichtkonformitäten'},{n:'9.2',t:'Internes Audit'},{n:'9.3',t:'Managementbewertung'},{n:'10.2',t:'Korrekturmaßnahmen'},{n:'10.3',t:'KVP'}]},
'ISO 45001':{m:'qm',fn:'ISO 45001:2018 – Arbeitsschutz',reqs:[{n:'5.2',t:'SGA-Politik'},{n:'5.4',t:'Arbeitnehmer-Konsultation'},{n:'6.1.2',t:'Gefährdungsidentifizierung'},{n:'6.2',t:'SGA-Ziele'},{n:'8.1',t:'Betriebliche Steuerung'},{n:'8.2',t:'Notfallplanung'},{n:'9.2',t:'Internes Audit'},{n:'10.2',t:'Vorfall/Korrektur'}]},
'COBIT 2019':{m:'itgov',fn:'COBIT 2019 – IT-Governance Framework',reqs:[{n:'EDM',t:'Evaluate, Direct and Monitor'},{n:'APO',t:'Align, Plan and Organize'},{n:'BAI',t:'Build, Acquire and Implement'},{n:'DSS',t:'Deliver, Service and Support'},{n:'MEA',t:'Monitor, Evaluate and Assess'}]},
'ISO/IEC 20000':{m:'itgov',fn:'ISO/IEC 20000-1 – IT Service Management',reqs:[{n:'4',t:'Kontext der Organisation'},{n:'5',t:'Leadership'},{n:'6',t:'Planning'},{n:'7',t:'Support of the SMS'},{n:'8',t:'Operation of the SMS'},{n:'9',t:'Performance Evaluation'},{n:'10',t:'Improvement'}]},
};

const CK=[
// ═══ SECURITY ═══
{id:'perimeter',l:'Perimeter & Gelände',l_en:'Perimeter & Premises',m:'security',norms:['ISO 31000','KRITIS-DachG','BSI IT-Grundschutz'],i:'EXT',s:'Außensicherung, Gelände, Beleuchtung.',items:[
{id:'p1',l:'Geländeeinfriedung',n:'DIN EN 1627 · BSI INF.1',d:'Zustand, Höhe ≥2m, Lückenfreiheit.',c:{mangel:'2.000–8.000',kritisch:'8.000–25.000'},m:'security'},
{id:'p2',l:'Fahrzeugsperre / Poller',n:'PAS 68 · IWA 14',d:'Rammschutz an Eingängen.',c:{mangel:'5.000–15.000',kritisch:'15.000–60.000'},m:'security'},
{id:'p3',l:'Geländebeleuchtung',n:'DIN EN 12464',d:'Lückenlose Ausleuchtung.',c:{mangel:'2.000–6.000',kritisch:'6.000–15.000'},m:'security'},
{id:'p4',l:'Beschilderung',n:'ASR A1.3',d:'Schilder komplett.',c:{mangel:'200–800',kritisch:'800–2.000'},m:'security'},
{id:'p5',l:'Drohnenabwehr',n:'KRITIS-DachG §13',d:'UAV-Schutz.',c:{mangel:'10.000–30.000',kritisch:'30.000–100.000'},m:'security'},
]},
{id:'zutritt',l:'Zutrittskontrolle',l_en:'Access Control',m:'security',norms:['ISO/IEC 27001','BSI IT-Grundschutz','NIS2'],i:'ACC',s:'ZKS, Schlüssel, Schleusen, Besucher.',items:[
{id:'z1',l:'Elektronische ZKS',n:'DIN VDE 0830-8',d:'Protokollierung, Karten/PIN/Bio.',c:{mangel:'5.000–15.000',kritisch:'15.000–40.000'},m:'security'},
{id:'z2',l:'Schlüsselverwaltung',n:'VdS 2311',d:'Register, Ausgabeprotokoll.',c:{mangel:'500–2.000',kritisch:'2.000–8.000'},m:'security'},
{id:'z3',l:'Einlassschleuse',n:'DIN EN 1627',d:'Vereinzelung Hochsicherheit.',c:{mangel:'8.000–20.000',kritisch:'20.000–60.000'},m:'security'},
{id:'z4',l:'Besuchermanagement',n:'ISO 27001 A.11',d:'Registrierung, Begleitpflicht.',c:{mangel:'1.000–4.000',kritisch:'4.000–10.000'},m:'security'},
{id:'z5',l:'Berechtigungskonzept',n:'ISO 27001 A.9',d:'Dokumentiert, geprüft.',c:{mangel:'1.500–4.000',kritisch:'4.000–8.000'},m:'security'},
]},
{id:'einbruch',l:'Einbruchhemmung',l_en:'Intrusion Prevention',m:'security',norms:['ISO 31000'],i:'EIN',s:'Türen, Fenster, Tresore.',items:[
{id:'e1',l:'Außentüren RC2+',n:'DIN EN 1627',d:'≥ RC2.',c:{mangel:'1.500–5.000',kritisch:'5.000–15.000'},m:'security'},
{id:'e2',l:'Fenster ≥ P6B',n:'EN 356',d:'EG einbruchhemmend.',c:{mangel:'2.000–8.000',kritisch:'8.000–25.000'},m:'security'},
{id:'e3',l:'Tresore',n:'EN 1143-1',d:'Zertifiziert, verankert.',c:{mangel:'2.000–6.000',kritisch:'6.000–20.000'},m:'security'},
]},
{id:'video',l:'Videoüberwachung',l_en:'Video Surveillance',m:'security',norms:['ISO/IEC 27001','BSI IT-Grundschutz'],i:'VID',s:'Kameras, Auflösung, Speicher, DSGVO.',items:[
{id:'v1',l:'Kamera Eingänge',n:'DIN EN 62676-4',d:'Identifikationsqualität.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'security'},
{id:'v2',l:'Innenraum',n:'DIN EN 62676-4',d:'Kritische Bereiche.',c:{mangel:'2.000–6.000',kritisch:'6.000–15.000'},m:'security'},
{id:'v3',l:'≥1080p',n:'DIN EN 62676-4',d:'Auflösung/Framerate.',c:{mangel:'4.000–12.000',kritisch:'12.000–30.000'},m:'security'},
{id:'v4',l:'Speicherung ≥72h',n:'VdS 2366',d:'Manipulationsschutz.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'security'},
{id:'v5',l:'DSGVO-Schilder',n:'DSGVO Art.13',d:'Hinweise vorhanden.',c:{mangel:'200–600',kritisch:'600–2.000'},m:'security'},
]},
{id:'alarm',l:'Alarm & Meldeanlagen',l_en:'Alarm Systems',m:'security',norms:['ISO 31000','BSI IT-Grundschutz'],i:'ALM',s:'EMA, ÜMA, NSL, Wartung.',items:[
{id:'a1',l:'EMA',n:'DIN EN 50131',d:'VdS-anerkannt.',c:{mangel:'5.000–15.000',kritisch:'15.000–40.000'},m:'security'},
{id:'a2',l:'NSL-Aufschaltung',n:'VdS 2311',d:'24/7.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'security'},
{id:'a3',l:'Bewegungsmelder',n:'DIN EN 50131-2',d:'PIR/Dual-Tech.',c:{mangel:'2.000–6.000',kritisch:'6.000–15.000'},m:'security'},
{id:'a4',l:'Wartungsnachweis',n:'VdS 2311',d:'Jährlich.',c:{mangel:'500–1.500',kritisch:'1.500–4.000'},m:'security'},
]},
{id:'brand',l:'Brandschutz',l_en:'Fire Protection',m:'security',norms:['ISO 45001','BSI IT-Grundschutz'],i:'BRD',s:'BMA, Löscher, Fluchtwege.',items:[
{id:'b1',l:'BMA',n:'DIN 14675',d:'Automatische Melder.',c:{mangel:'8.000–25.000',kritisch:'25.000–80.000'},m:'security'},
{id:'b2',l:'Feuerlöscher',n:'DIN EN 3',d:'Geprüft, korrekte Klassen.',c:{mangel:'500–2.000',kritisch:'2.000–6.000'},m:'security'},
{id:'b3',l:'Fluchtwege',n:'ASR A2.3',d:'Frei, gekennzeichnet.',c:{mangel:'1.000–4.000',kritisch:'4.000–12.000'},m:'security'},
{id:'b4',l:'Brandschutzordnung',n:'DIN 14096',d:'Teil A/B/C aktuell.',c:{mangel:'800–2.500',kritisch:'2.500–6.000'},m:'security'},
]},
{id:'orga',l:'Sicherheitsorganisation',l_en:'Security Organisation',m:'security',norms:['ISO 31000','ISO/IEC 27001','ISO 22301','NIS2','KRITIS-DachG'],i:'ORG',s:'Richtlinien, Schulungen, BCM.',items:[
{id:'o1',l:'Sicherheitsrichtlinie',n:'ISO 27001 A.5',d:'GF-unterzeichnet.',c:{mangel:'2.000–5.000',kritisch:'5.000–10.000'},m:'security'},
{id:'o2',l:'Security Awareness',n:'BSI ORP.3',d:'Regelmäßig.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'security'},
{id:'o3',l:'Notfall-/Krisenplan',n:'ISO 22301 §8.4',d:'Getestet.',c:{mangel:'4.000–10.000',kritisch:'10.000–25.000'},m:'security'},
{id:'o4',l:'BIA',n:'ISO 22301 §8.2',d:'RTO/RPO festgelegt.',c:{mangel:'3.000–8.000',kritisch:'8.000–18.000'},m:'security'},
{id:'o5',l:'Meldepflicht-Prozess',n:'NIS2 §31',d:'24h/72h definiert.',c:{mangel:'1.000–3.000',kritisch:'3.000–8.000'},m:'security'},
]},
{id:'religion',l:'Religionsgemeinschaften',l_en:'Religious Institutions',m:'religion',norms:['ISO 31000','NIS2','KRITIS-DachG'],i:'REL',s:'Sicherheitsanforderungen für religiöse Einrichtungen im Umfeld.',s_en:'Security requirements for religious institutions in the vicinity.',items:[
{id:'rel1',l:'Synagoge / Jüdische Einrichtung',l_en:'Synagogue / Jewish Institution',n:'ISO 31000 · KRITIS-DachG §13',d:'Jüdische Einrichtung im Umfeld – polizeilicher Schutzstatus prüfen, erhöhte Zutrittskontrolle, Videoüberwachung, Perimeterschutz. Häufig unter Polizeibegleitung und Sonderschutz.',d_en:'Jewish institution in vicinity – check police protection status, enhanced access control, CCTV, perimeter protection. Often under police escort and special protection.',c:{mangel:'3.000–8.000',kritisch:'8.000–25.000'},m:'security'},
{id:'rel2',l:'Moschee / Islamische Einrichtung',l_en:'Mosque / Islamic Institution',n:'ISO 31000',d:'Islamische Einrichtung im Umfeld – erhöhte Wachsamkeit gegenüber Hasskriminalität. Videoüberwachung an Eingängen, gute Beleuchtung, Kontakt zur Polizei empfohlen.',d_en:'Islamic institution in vicinity – heightened vigilance against hate crime. CCTV at entrances, good lighting, police contact recommended.',c:{mangel:'2.000–6.000',kritisch:'6.000–15.000'},m:'security'},
{id:'rel3',l:'Kirche / Dom / Kapelle',l_en:'Church / Cathedral / Chapel',n:'ISO 31000',d:'Christliche Einrichtung im Umfeld. Bei Großveranstaltungen erhöhte Personenströme und besondere Sicherheitsmaßnahmen berücksichtigen.',d_en:'Christian institution in vicinity. Account for high foot traffic and special security measures during large events.',c:{mangel:'1.000–3.000',kritisch:'3.000–8.000'},m:'security'},
{id:'rel4',l:'Tempel / Sonstige Religionsgemeinschaft',l_en:'Temple / Other Religious Community',n:'ISO 31000',d:'Sonstige religiöse Einrichtung im Umfeld. Kulturelle Sensibilität und angepasste Sicherheitsmaßnahmen beachten.',d_en:'Other religious institution in vicinity. Cultural sensitivity and adapted security measures required.',c:{mangel:'1.000–3.000',kritisch:'3.000–8.000'},m:'security'},
{id:'rel5',l:'Polizeilicher Schutz koordiniert',l_en:'Police Protection Coordinated',n:'KRITIS-DachG §13',d:'Regelmäßige Abstimmung mit der zuständigen Polizeidienststelle bzgl. Schutzbedarfs und Lagebeurteilung erfolgt.',d_en:'Regular coordination with the responsible police authority regarding protection needs and situational assessment carried out.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'security'},
{id:'rel6',l:'Notfallplan für politisch motivierte Gewalt',l_en:'Emergency Plan for Politically Motivated Violence',n:'ISO 22301 · NIS2',d:'Spezifischer Notfallplan für Anschlagsszenarien, Hasskriminalität und politisch motivierte Gewalt vorhanden und geübt.',d_en:'Specific emergency plan for attack scenarios, hate crime and politically motivated violence exists and has been rehearsed.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'security'},
]},
// ═══ QM ═══
{id:'qm_kf',l:'Kontext & Führung',l_en:'Context & Leadership',m:'qm',norms:['ISO 9001','ISO 45001'],i:'KON',s:'Kontext, Parteien, Politik.',items:[
{id:'q1',l:'Kontext',n:'ISO 9001 4.1',d:'Themen identifiziert.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'qm'},
{id:'q2',l:'Interessierte Parteien',n:'ISO 9001 4.2',d:'Stakeholder-Analyse.',c:{mangel:'1.000–3.000',kritisch:'3.000–8.000'},m:'qm'},
{id:'q3',l:'Qualitätspolitik',n:'ISO 9001 5.2',d:'Kommuniziert.',c:{mangel:'1.000–3.000',kritisch:'3.000–6.000'},m:'qm'},
{id:'q4',l:'Rollen & Verantwortung',n:'ISO 9001 5.3',d:'Organigramm.',c:{mangel:'1.500–4.000',kritisch:'4.000–8.000'},m:'qm'},
]},
{id:'qm_plan',l:'Planung & Risiken',l_en:'Planning & Risks',m:'qm',norms:['ISO 9001','ISO 45001'],i:'PLN',s:'Risikobewertung, Ziele, Gefährdungsbeurteilung.',items:[
{id:'qp1',l:'Risiken & Chancen',n:'ISO 9001 6.1',d:'Systematisch bewertet.',c:{mangel:'2.000–6.000',kritisch:'6.000–15.000'},m:'qm'},
{id:'qp2',l:'Qualitätsziele SMART',n:'ISO 9001 6.2',d:'Messbar, nachverfolgt.',c:{mangel:'1.000–3.000',kritisch:'3.000–6.000'},m:'qm'},
{id:'qp3',l:'Gefährdungsbeurteilung',n:'ISO 45001 6.1.2',d:'Alle Arbeitsplätze.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'qm'},
{id:'qp4',l:'Rechtskataster',n:'ISO 45001 6.1.3',d:'Aktuell.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'qm'},
]},
{id:'qm_res',l:'Ressourcen & Kompetenz',l_en:'Resources & Competence',m:'qm',norms:['ISO 9001','ISO 45001'],i:'RES',s:'Personal, Schulung, Dokumentation.',items:[
{id:'qs1',l:'Kompetenz',n:'ISO 9001 7.2',d:'Schulungsplan, Nachweise.',c:{mangel:'2.000–6.000',kritisch:'6.000–15.000'},m:'qm'},
{id:'qs2',l:'Dokumentenlenkung',n:'ISO 9001 7.5',d:'Erstellen, Genehmigen.',c:{mangel:'2.000–5.000',kritisch:'5.000–10.000'},m:'qm'},
]},
{id:'qm_op',l:'Betrieb & Steuerung',l_en:'Operations & Control',m:'qm',norms:['ISO 9001','ISO 45001'],i:'BET',s:'Planung, Lieferanten, Nichtkonformitäten.',items:[
{id:'qb1',l:'Betriebliche Planung',n:'ISO 9001 8.1',d:'Prozesse gesteuert.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'qm'},
{id:'qb2',l:'Lieferantensteuerung',n:'ISO 9001 8.4',d:'Bewertung, Überwachung.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'qm'},
{id:'qb3',l:'Nichtkonformitäten',n:'ISO 9001 8.7',d:'Identifiziert, korrigiert.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'qm'},
]},
{id:'qm_kvp',l:'Bewertung & KVP',l_en:'Evaluation & CIP',m:'qm',norms:['ISO 9001','ISO 45001'],i:'KVP',s:'Audits, Managementbewertung, KVP.',items:[
{id:'qv1',l:'Internes Audit',n:'ISO 9001 9.2',d:'Auditplan, Berichte.',c:{mangel:'3.000–8.000',kritisch:'8.000–18.000'},m:'qm'},
{id:'qv2',l:'Managementbewertung',n:'ISO 9001 9.3',d:'Jährlich.',c:{mangel:'2.000–5.000',kritisch:'5.000–10.000'},m:'qm'},
{id:'qv3',l:'KVP-Prozess',n:'ISO 9001 10.3',d:'Systematisch.',c:{mangel:'1.500–4.000',kritisch:'4.000–8.000'},m:'qm'},
]},
// ═══ IT-GOVERNANCE (COBIT) ═══
{id:'itg_org',l:'1. IT-Organisation',l_en:'1. IT Organisation',m:'itgov',norms:['COBIT 2019','ISO/IEC 20000'],i:'ORG',s:'Rollen, Verantwortlichkeiten, Personalbedarf.',items:[
{id:'c01',l:'Rollen & Verantwortlichkeiten IT',n:'APO01.05',d:'IT-Organigramm, Stellenbeschreibungen.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Leadership',rd:'IT-Organigramm; IT-Stellenbeschreibungen',f:'J'},
{id:'c02',l:'Personalbedarf regelmäßig bewertet',n:'APO01.08',d:'Prozess zur Bewertung des IT-Personalbedarfs.',c:{mangel:'1.000–3.000',kritisch:'3.000–8.000'},m:'itgov',iso20k:'Support – Resources',rd:'Personalbedarfsanalyse',f:'J'},
{id:'c03',l:'Zielkompetenzen IT-Personal',n:'APO01.08',d:'Kompetenzprofile, Weiterbildungsplan.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'itgov',iso20k:'Support – Competence',rd:'Kompetenzmatrix; Schulungsplan',f:'J'},
]},
{id:'itg_strat',l:'2. IT-Strategie',l_en:'2. IT Strategy',m:'itgov',norms:['COBIT 2019','ISO/IEC 20000'],i:'STR',s:'Strategieplan, KPIs, Stakeholder-Genehmigung.',items:[
{id:'c04',l:'IT-Strategie dokumentiert',n:'APO02.05',d:'Ganzheitliche IT-Strategie und Roadmap.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'itgov',iso20k:'Planning – Objectives',rd:'IT-Strategiedokument',f:'J'},
{id:'c05',l:'IT-KPIs messbar definiert',n:'APO02.05',d:'Strategische Ziele in messbare KPIs übersetzt.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'itgov',iso20k:'Planning – Objectives',rd:'KPI-Maßnahmenplan',f:'Q'},
{id:'c06',l:'IT-Strategie genehmigt',n:'APO02.05',d:'Formale Genehmigung durch Stakeholder/GF.',c:{mangel:'1.000–3.000',kritisch:'3.000–6.000'},m:'itgov',iso20k:'Planning – Plan the SMS',rd:'Genehmigungsnachweis',f:'J'},
]},
{id:'itg_isms',l:'3. Informationssicherheit',l_en:'3. Information Security',m:'itgov',norms:['COBIT 2019','ISO/IEC 20000','ISO/IEC 27001'],i:'SEC',s:'ISMS, Richtlinien, SOA, Audits, Reporting.',items:[
{id:'c07',l:'ISMS-Rollen definiert',n:'APO13.01',d:'Informationssicherheitsbeauftragter benannt.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'itgov',iso20k:'Service Assurance',rd:'Rollenbeschreibung ISO',f:'J'},
{id:'c08',l:'Informationssicherheits-Policy',n:'APO13.01',d:'Von Management genehmigte Policy.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Service Management Policy',rd:'Informationssicherheits-Policy',f:'J'},
{id:'c09',l:'Sicherheitsrichtlinien abgeleitet',n:'APO13.02',d:'Spezifische Richtlinien aus Policy abgeleitet.',c:{mangel:'2.000–5.000',kritisch:'5.000–10.000'},m:'itgov',iso20k:'Service Assurance',rd:'Sicherheitsrichtlinien',f:'J'},
{id:'c10',l:'Statement of Applicability',n:'APO13.01',d:'SOA vorhanden, Scope definiert.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Service Assurance',rd:'Statement of Applicability (SOA)',f:'J'},
{id:'c11',l:'ISMS-Audits durchgeführt',n:'APO13.03',d:'Regelmäßige ISMS-Reviews und Audits.',c:{mangel:'3.000–8.000',kritisch:'8.000–18.000'},m:'itgov',iso20k:'Service Assurance',rd:'ISMS-Auditberichte',f:'J'},
{id:'c12',l:'ISMS-Reporting an Management',n:'APO13.03',d:'Regelmäßige Berichte an GF.',c:{mangel:'1.000–3.000',kritisch:'3.000–6.000'},m:'itgov',iso20k:'Communication',rd:'ISMS-Management-Reports',f:'Q'},
]},
{id:'itg_risk',l:'4. IT-Risikomanagement',l_en:'4. IT Risk Management',m:'itgov',norms:['COBIT 2019','ISO/IEC 20000'],i:'RSK',s:'Risiko-Policy, Assets, Schutzbedarfe, Reports.',items:[
{id:'c13',l:'IT-Risikomanagement-Policy',n:'APO12.01',d:'Methode zur Risikoerfassung etabliert.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Risks and Opportunities',rd:'IT-Risikomanagement-Policy',f:'J'},
{id:'c14',l:'IT-Asset-Inventar',n:'APO12.03',d:'Geschäftsprozesse und IT-Assets inventarisiert.',c:{mangel:'2.000–6.000',kritisch:'6.000–15.000'},m:'itgov',iso20k:'Service Portfolio',rd:'IT-Asset-Inventar; Prozesslandschaft',f:'Q'},
{id:'c15',l:'Schutzbedarfsfeststellung',n:'APO12.03',d:'Schutzniveaus für IT-Services festgelegt.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Risks and Opportunities',rd:'Schutzbedarfsfeststellung',f:'J'},
{id:'c16',l:'IT-Risiko-Report',n:'APO12.04',d:'Risikoanalyse-Ergebnisse an Stakeholder.',c:{mangel:'1.500–4.000',kritisch:'4.000–8.000'},m:'itgov',iso20k:'Risks and Opportunities',rd:'IT-Risiko-Report',f:'Q'},
{id:'c17',l:'Risikominderungsplan',n:'APO12.05',d:'Kontrollaktivitäten inventarisiert.',c:{mangel:'2.000–5.000',kritisch:'5.000–10.000'},m:'itgov',iso20k:'Risks and Opportunities',rd:'Risikominderungsplan',f:'Q'},
{id:'c18',l:'Audit-Feststellungen nachverfolgt',n:'MEA03.03',d:'Remediation Tracking vorhanden.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'itgov',iso20k:'Performance Evaluation',rd:'Maßnahmenlisten; Remediation Tracking',f:'Q'},
]},
{id:'itg_inc',l:'5. Incident-Management',l_en:'5. Incident Management',m:'itgov',norms:['COBIT 2019','ISO/IEC 20000'],i:'INC',s:'Incident-Prozess, Tickets, Reporting.',items:[
{id:'c19',l:'Incident-Management-Prozess',n:'DSS02.02',d:'Klassifizierung, Priorisierung, Eskalation.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'itgov',iso20k:'Resolution and Fulfilment',rd:'Incident-Policy; Eskalationsregeln; Klassifizierung',f:'O'},
{id:'c20',l:'Incident-Analyse & Diagnose',n:'DSS02.04',d:'Symptome identifiziert, Root-Cause-Analyse.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Resolution and Fulfilment',rd:'Incident-Tickets; Incident-Log',f:'O'},
{id:'c21',l:'Incident-Reporting & Trends',n:'DSS02.07',d:'Regelmäßige Statusberichte und Trendanalyse.',c:{mangel:'1.500–4.000',kritisch:'4.000–8.000'},m:'itgov',iso20k:'Resolution and Fulfilment',rd:'Incident-Status-Reports; Trendberichte',f:'M'},
]},
{id:'itg_access',l:'6. Logischer Zugriff',l_en:'6. Logical Access',m:'itgov',norms:['COBIT 2019','ISO/IEC 20000','ISO/IEC 27001'],i:'ZGR',s:'Berechtigungen, Passwörter, privilegierte Accounts.',items:[
{id:'c22',l:'Zugriffs-Policy & Verfahren',n:'DSS05.04',d:'Richtlinien für Vergabe/Änderung/Entzug.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Service Assurance',rd:'User-Access-Policy; Berechtigungskonzept',f:'J'},
{id:'c23',l:'Änderungen an Zugriffsrechten',n:'DSS05.04',d:'Erstellung/Änderung/Löschung dokumentiert.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'itgov',iso20k:'Service Assurance',rd:'Genehmigte Zugriffsanträge',f:'O'},
{id:'c24',l:'Privilegierte Accounts',n:'DSS05.04',d:'Nur autorisierte Administratoren.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'itgov',iso20k:'Service Assurance',rd:'Admin-Rollenkonzept',f:'Q'},
{id:'c25',l:'Personalisierte Accounts',n:'DSS05.04',d:'Keine generischen Accounts für Enduser.',c:{mangel:'1.000–3.000',kritisch:'3.000–8.000'},m:'itgov',iso20k:'Service Assurance',rd:'Active Directory; Service-Account-Übersicht',f:'Q'},
{id:'c26',l:'Passwort-Richtlinie',n:'DSS05.04',d:'Authentifizierung, Komplexität, MFA.',c:{mangel:'1.000–3.000',kritisch:'3.000–8.000'},m:'itgov',iso20k:'Service Assurance',rd:'Passwort-Guideline',f:'J'},
{id:'c27',l:'Jährlicher Account-Review',n:'DSS05.04',d:'Alle Accounts und Berechtigungen überprüft.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Service Assurance',rd:'Account-Review-Dokumentation',f:'J'},
]},
{id:'itg_phys',l:'7. Physischer IT-Zugriff',l_en:'7. Physical IT Access',m:'itgov',norms:['COBIT 2019','ISO/IEC 20000'],i:'EIN',s:'Serverraum-Zugang, Besucherlogbuch, Autorisierung.',items:[
{id:'c28',l:'Perimeter-Schutz IT-Bereiche',n:'DSS05.05',d:'Zugang einschränken und überwachen.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'itgov',iso20k:'Service Assurance',rd:'Zugangskonzept IT-Räume',f:'Q'},
{id:'c29',l:'Besucher-Registrierung IT',n:'DSS05.05',d:'Alle Besucher/Dienstleister registriert.',c:{mangel:'500–2.000',kritisch:'2.000–5.000'},m:'itgov',iso20k:'Service Assurance',rd:'Besucherlogbuch',f:'O'},
{id:'c30',l:'Zugangsgenehmigung IT-Bereiche',n:'DSS05.05',d:'Zugangsanträge genehmigt und autorisiert.',c:{mangel:'1.000–3.000',kritisch:'3.000–8.000'},m:'itgov',iso20k:'Service Assurance',rd:'Genehmigte Zugangsanträge',f:'O'},
{id:'c31',l:'Zugangs-Review IT-Räume',n:'DSS05.05',d:'Autorisierungen regelmäßig überprüft.',c:{mangel:'1.000–3.000',kritisch:'3.000–6.000'},m:'itgov',iso20k:'Service Assurance',rd:'Review-Ergebnisse',f:'Q'},
{id:'c32',l:'Zugangs-Logs ausgewertet',n:'DSS05.07',d:'Protokolle regelmäßig evaluiert.',c:{mangel:'1.000–3.000',kritisch:'3.000–8.000'},m:'itgov',iso20k:'Service Assurance',rd:'Zugangs-Logs; Auswertungen',f:'M'},
]},
{id:'itg_physec',l:'8. Physische IT-Sicherheit',l_en:'8. Physical IT Security',m:'itgov',norms:['COBIT 2019','ISO/IEC 20000'],i:'INF',s:'USV, Klima, Wartung, Umgebungsschutz.',items:[
{id:'c33',l:'Sauberkeit & Sicherheit IT-Räume',n:'DSS01.04',d:'Ordnung, Brandlasten minimiert.',c:{mangel:'500–2.000',kritisch:'2.000–6.000'},m:'itgov',iso20k:'Service Assurance',rd:'Begehungsprotokolle',f:'Q'},
{id:'c34',l:'Umgebungsschutz Serverraum',n:'DSS01.04',d:'Gegen Umwelteinflüsse geschützt.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'itgov',iso20k:'Service Assurance',rd:'Security-Policy IT-Facilities',f:'J'},
{id:'c35',l:'Umgebungsüberwachung',n:'DSS01.04',d:'Klima, Feuchte, Temperatur-Monitoring.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Service Assurance',rd:'Monitoring-Protokolle',f:'M'},
{id:'c36',l:'USV-Tests',n:'DSS01.05',d:'Regelmäßige USV-Tests dokumentiert.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'itgov',iso20k:'Service Assurance',rd:'USV-Testprotokolle',f:'Q'},
{id:'c37',l:'Redundante Stromversorgung',n:'DSS01.05',d:'Mehr als eine Stromquelle.',c:{mangel:'5.000–15.000',kritisch:'15.000–40.000'},m:'itgov',iso20k:'Service Assurance',rd:'Infrastruktur-Dokumentation',f:'J'},
{id:'c38',l:'Wartungsverträge IT-Infrastruktur',n:'DSS01.05',d:'Herstellervorgaben eingehalten.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Service Assurance',rd:'Wartungspläne; Wartungsverträge',f:'J'},
]},
{id:'itg_dev',l:'9. Anwendungsentwicklung',l_en:'9. Application Development',m:'itgov',norms:['COBIT 2019','ISO/IEC 20000'],i:'DEV',s:'Change Management, Testing, Release, CMDB.',items:[
{id:'c39',l:'Entwicklungs-/Change-Richtlinie',n:'BAI03.02',d:'Standardisiertes Verfahren.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'itgov',iso20k:'Design Build and Transition',rd:'Change-Management-Guideline; Rollen/Verantwortlichkeiten',f:'J'},
{id:'c40',l:'Anforderungsdokumentation',n:'BAI03.02',d:'Funktionale/nicht-funktionale Anforderungen.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'itgov',iso20k:'Design Build and Transition',rd:'Anforderungsdokumente; Genehmigungsnachweise',f:'O'},
{id:'c41',l:'Getrennte Entwicklungs-/Testumgebung',n:'BAI03.03',d:'Dev/Test separat von Produktion.',c:{mangel:'2.000–6.000',kritisch:'6.000–15.000'},m:'itgov',iso20k:'Design Build and Transition',rd:'Umgebungs-Dokumentation',f:'J'},
{id:'c42',l:'Versionierung & Dokumentation',n:'BAI03.03',d:'Coding Guidelines, Versionskontrolle.',c:{mangel:'1.500–4.000',kritisch:'4.000–8.000'},m:'itgov',iso20k:'Design Build and Transition',rd:'Coding Guidelines; Changelog',f:'O'},
{id:'c43',l:'Testplan & -verfahren',n:'BAI03.07',d:'Testplan, Testumgebung definiert.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Design Build and Transition',rd:'Testplan; Testprozeduren',f:'O'},
{id:'c44',l:'Testdurchführung dokumentiert',n:'BAI03.08',d:'Testergebnisse, Bug-Listen.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'itgov',iso20k:'Design Build and Transition',rd:'Testergebnisse; Bug-Listen',f:'O'},
{id:'c45',l:'Release-/Konfigurationsmanagement',n:'BAI03.09',d:'CMDB, Change-Tracking in Produktion.',c:{mangel:'2.000–6.000',kritisch:'6.000–15.000'},m:'itgov',iso20k:'Design Build and Transition',rd:'CMDB; Produktions-Changelog',f:'O'},
]},
{id:'itg_mon',l:'10. Infrastruktur-Monitoring',l_en:'10. Infrastructure Monitoring',m:'itgov',norms:['COBIT 2019','ISO/IEC 20000'],i:'MON',s:'Performance- und Kapazitätsüberwachung.',items:[
{id:'c46',l:'IT-Infrastruktur-Monitoring',n:'DSS01.03',d:'Performance/Kapazität kontinuierlich überwacht.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'itgov',iso20k:'Service Portfolio',rd:'Monitoring-Regeln; Incident-Tickets aus Monitoring',f:'O'},
]},
{id:'itg_malware',l:'11. Schutz vor Schadsoftware',l_en:'11. Malware Protection',m:'itgov',norms:['COBIT 2019','ISO/IEC 20000'],i:'MAL',s:'Anti-Malware, Penetration Tests, Awareness, Endpoints.',items:[
{id:'c47',l:'Anti-Malware aktiv',n:'DSS05.01',d:'Auf allen Systemen installiert/aktiv.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Service Assurance',rd:'Anti-Malware-Policy',f:'O'},
{id:'c48',l:'Traffic-Filterung & Penetration Tests',n:'DSS05.01',d:'E-Mail/Download-Filter, regelmäßige Pentests.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'itgov',iso20k:'Service Assurance',rd:'Pentest-Ergebnisse',f:'J'},
{id:'c49',l:'Security-Awareness-Programm',n:'DSS05.01',d:'Mitarbeiter geschult, Präventionsmaßnahmen.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Service Assurance',rd:'Security-Awareness-Programm; Schulungsnachweise',f:'J'},
{id:'c50',l:'Endpoint-Sicherheit',n:'DSS05.03',d:'Endpoints konfiguriert, Netzwerktrennung.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'itgov',iso20k:'Service Assurance',rd:'Endpoint-Security-Policies',f:'Q'},
]},
{id:'itg_vendor',l:'12. Auslagerung & Vendor Mgmt',l_en:'12. Outsourcing & Vendor Mgmt',m:'itgov',norms:['COBIT 2019','ISO/IEC 20000'],i:'VND',s:'Lieferantenauswahl, Risikobewertung, SLA-Monitoring.',items:[
{id:'c51',l:'Vendor-Management-Prozess',n:'APO10.01',d:'Auswahl, Bewertung, Katalog.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Relationship and Agreement',rd:'Vendor-Policy; Lieferantenkatalog',f:'J'},
{id:'c52',l:'Vendor-Risikobewertung',n:'APO10.04',d:'Third-Party-Risk-Assessment.',c:{mangel:'2.000–6.000',kritisch:'6.000–15.000'},m:'itgov',iso20k:'Relationship and Agreement',rd:'Third-Party-Risk-Reports',f:'J'},
{id:'c53',l:'Vendor-Performance-Monitoring',n:'APO10.05',d:'SLA-Überwachung, Compliance-Check.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'itgov',iso20k:'Relationship and Agreement',rd:'Vendor-Compliance-Reports',f:'Q'},
]},
{id:'itg_bcm',l:'13. BCM & Backup',l_en:'13. BCM & Backup',m:'itgov',norms:['COBIT 2019','ISO/IEC 20000','ISO 22301'],i:'BCM',s:'BIA, BCP, DRP, Backup-Tests.',items:[
{id:'c54',l:'Business Impact Analyse (IT)',n:'DSS04.02',d:'BIA für IT-Prozesse.',c:{mangel:'3.000–8.000',kritisch:'8.000–20.000'},m:'itgov',iso20k:'Service Assurance',rd:'Business Impact Analyse',f:'J'},
{id:'c55',l:'BCP & DRP vorhanden',n:'DSS04.03',d:'Business Continuity & Disaster Recovery Plan.',c:{mangel:'4.000–10.000',kritisch:'10.000–25.000'},m:'itgov',iso20k:'Service Assurance',rd:'BCP; DRP',f:'J'},
{id:'c56',l:'BCP/DRP getestet',n:'DSS04.04',d:'Übungen durchgeführt, Ergebnisse dokumentiert.',c:{mangel:'2.000–6.000',kritisch:'6.000–15.000'},m:'itgov',iso20k:'Service Assurance',rd:'BCM-Testergebnisse',f:'J'},
{id:'c57',l:'BCM-Pläne aktuell',n:'DSS04.05',d:'Management-Review, kontinuierliche Pflege.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'itgov',iso20k:'Service Assurance',rd:'BCM-Review-Ergebnisse',f:'J'},
{id:'c58',l:'Backup-Policy',n:'DSS04.07',d:'Definierter Backup-Zeitplan.',c:{mangel:'1.500–4.000',kritisch:'4.000–10.000'},m:'itgov',iso20k:'Service Assurance',rd:'Backup-Policy; Backup-Protokolle',f:'M'},
{id:'c59',l:'Backup-Restore-Tests',n:'DSS04.07',d:'Regelmäßige Wiederherstellungstests.',c:{mangel:'2.000–5.000',kritisch:'5.000–12.000'},m:'itgov',iso20k:'Service Assurance',rd:'Restore-Testergebnisse',f:'Q'},
]},
];

const CATS=['Richtlinie','Zertifikat','Protokoll','Schulung','Wartung','Vertrag','Plan','Analyse','Sonstiges'];
const CATI={Richtlinie:'RL',Zertifikat:'ZT',Protokoll:'PR',Schulung:'SH',Wartung:'WT',Vertrag:'VT',Plan:'PL',Analyse:'AN',Sonstiges:'SO'};
const FREQ_LABEL={J:'Jährlich',Q:'Quartalsweise',M:'Monatlich',O:'Operativ/Laufend'};
const TEMPLATES=[
{id:'logistik',name:'Logistik',name_en:'Logistics',icon:'LOG',desc:'Perimeter, Zutritt, Brand, QM.',desc_en:'Perimeter, access, fire, QM.',mod:'combined'},
{id:'buero',name:'Büro',name_en:'Office',icon:'OFF',desc:'Zutritt, IT, Brand, QM.',desc_en:'Access, IT, fire, QM.',mod:'combined'},
{id:'produktion',name:'Produktion',name_en:'Production',icon:'PRD',desc:'Arbeitsschutz, QM komplett.',desc_en:'Workplace safety, full QM.',mod:'qm'},
{id:'kritis',name:'KRITIS',name_en:'KRITIS',icon:'KRI',desc:'Maximaler Umfang.',desc_en:'Maximum scope.',mod:'combined'},
{id:'gemeinde',name:'Gemeinde / Kommunal',name_en:'Municipality',icon:'GOV',desc:'Öffentliche Gebäude, Bürgerämter, kommunale Verwaltung.',desc_en:'Public buildings, civic centers, municipal administration.',mod:'combined'},
{id:'it',name:'IT / RZ',name_en:'IT / DC',icon:'ITG',desc:'IT-Governance + Security.',desc_en:'IT Governance + Security.',mod:'itgov'},
{id:'religion',name:'Religionsgemeinschaften',name_en:'Religious Institutions',icon:'REL',desc:'Sicherheit für religiöse Einrichtungen.',desc_en:'Security for religious institutions.',mod:'religion'},
];

// ═══ LÄNDER (ISO 3166-1, Deutsch) ═══
// DACH zuerst, dann alphabetisch
const COUNTRIES=[
  {code:'DE',de:'Deutschland',en:'Germany'},
  {code:'AT',de:'Österreich',en:'Austria'},
  {code:'CH',de:'Schweiz',en:'Switzerland'},
  {code:'LI',de:'Liechtenstein',en:'Liechtenstein'},
  {code:'LU',de:'Luxemburg',en:'Luxembourg'},
  {code:'──',de:'──────────────',en:'──────────────',disabled:true},
  {code:'AF',de:'Afghanistan',en:'Afghanistan'},
  {code:'AL',de:'Albanien',en:'Albania'},
  {code:'DZ',de:'Algerien',en:'Algeria'},
  {code:'AD',de:'Andorra',en:'Andorra'},
  {code:'AO',de:'Angola',en:'Angola'},
  {code:'AG',de:'Antigua und Barbuda',en:'Antigua and Barbuda'},
  {code:'AR',de:'Argentinien',en:'Argentina'},
  {code:'AM',de:'Armenien',en:'Armenia'},
  {code:'AZ',de:'Aserbaidschan',en:'Azerbaijan'},
  {code:'ET',de:'Äthiopien',en:'Ethiopia'},
  {code:'AU',de:'Australien',en:'Australia'},
  {code:'BS',de:'Bahamas',en:'Bahamas'},
  {code:'BH',de:'Bahrain',en:'Bahrain'},
  {code:'BD',de:'Bangladesch',en:'Bangladesh'},
  {code:'BB',de:'Barbados',en:'Barbados'},
  {code:'BY',de:'Belarus',en:'Belarus'},
  {code:'BE',de:'Belgien',en:'Belgium'},
  {code:'BZ',de:'Belize',en:'Belize'},
  {code:'BJ',de:'Benin',en:'Benin'},
  {code:'BT',de:'Bhutan',en:'Bhutan'},
  {code:'BO',de:'Bolivien',en:'Bolivia'},
  {code:'BA',de:'Bosnien und Herzegowina',en:'Bosnia and Herzegovina'},
  {code:'BW',de:'Botsuana',en:'Botswana'},
  {code:'BR',de:'Brasilien',en:'Brazil'},
  {code:'BN',de:'Brunei',en:'Brunei'},
  {code:'BG',de:'Bulgarien',en:'Bulgaria'},
  {code:'BF',de:'Burkina Faso',en:'Burkina Faso'},
  {code:'BI',de:'Burundi',en:'Burundi'},
  {code:'CL',de:'Chile',en:'Chile'},
  {code:'CN',de:'China',en:'China'},
  {code:'CR',de:'Costa Rica',en:'Costa Rica'},
  {code:'CI',de:"Côte d'Ivoire",en:"Côte d'Ivoire"},
  {code:'DK',de:'Dänemark',en:'Denmark'},
  {code:'CD',de:'Demokratische Republik Kongo',en:'DR Congo'},
  {code:'DO',de:'Dominikanische Republik',en:'Dominican Republic'},
  {code:'DJ',de:'Dschibuti',en:'Djibouti'},
  {code:'EC',de:'Ecuador',en:'Ecuador'},
  {code:'SV',de:'El Salvador',en:'El Salvador'},
  {code:'ER',de:'Eritrea',en:'Eritrea'},
  {code:'EE',de:'Estland',en:'Estonia'},
  {code:'SZ',de:'Eswatini',en:'Eswatini'},
  {code:'FJ',de:'Fidschi',en:'Fiji'},
  {code:'FI',de:'Finnland',en:'Finland'},
  {code:'FR',de:'Frankreich',en:'France'},
  {code:'GA',de:'Gabun',en:'Gabon'},
  {code:'GM',de:'Gambia',en:'Gambia'},
  {code:'GE',de:'Georgien',en:'Georgia'},
  {code:'GH',de:'Ghana',en:'Ghana'},
  {code:'GD',de:'Grenada',en:'Grenada'},
  {code:'GR',de:'Griechenland',en:'Greece'},
  {code:'GT',de:'Guatemala',en:'Guatemala'},
  {code:'GN',de:'Guinea',en:'Guinea'},
  {code:'GW',de:'Guinea-Bissau',en:'Guinea-Bissau'},
  {code:'GY',de:'Guyana',en:'Guyana'},
  {code:'HT',de:'Haiti',en:'Haiti'},
  {code:'HN',de:'Honduras',en:'Honduras'},
  {code:'IN',de:'Indien',en:'India'},
  {code:'ID',de:'Indonesien',en:'Indonesia'},
  {code:'IQ',de:'Irak',en:'Iraq'},
  {code:'IR',de:'Iran',en:'Iran'},
  {code:'IE',de:'Irland',en:'Ireland'},
  {code:'IS',de:'Island',en:'Iceland'},
  {code:'IL',de:'Israel',en:'Israel'},
  {code:'IT',de:'Italien',en:'Italy'},
  {code:'JM',de:'Jamaika',en:'Jamaica'},
  {code:'JP',de:'Japan',en:'Japan'},
  {code:'YE',de:'Jemen',en:'Yemen'},
  {code:'JO',de:'Jordanien',en:'Jordan'},
  {code:'KH',de:'Kambodscha',en:'Cambodia'},
  {code:'CM',de:'Kamerun',en:'Cameroon'},
  {code:'CA',de:'Kanada',en:'Canada'},
  {code:'CV',de:'Kap Verde',en:'Cape Verde'},
  {code:'KZ',de:'Kasachstan',en:'Kazakhstan'},
  {code:'QA',de:'Katar',en:'Qatar'},
  {code:'KE',de:'Kenia',en:'Kenya'},
  {code:'KG',de:'Kirgisistan',en:'Kyrgyzstan'},
  {code:'KI',de:'Kiribati',en:'Kiribati'},
  {code:'CO',de:'Kolumbien',en:'Colombia'},
  {code:'KM',de:'Komoren',en:'Comoros'},
  {code:'CG',de:'Kongo',en:'Republic of the Congo'},
  {code:'HR',de:'Kroatien',en:'Croatia'},
  {code:'CU',de:'Kuba',en:'Cuba'},
  {code:'KW',de:'Kuwait',en:'Kuwait'},
  {code:'LA',de:'Laos',en:'Laos'},
  {code:'LS',de:'Lesotho',en:'Lesotho'},
  {code:'LV',de:'Lettland',en:'Latvia'},
  {code:'LB',de:'Libanon',en:'Lebanon'},
  {code:'LR',de:'Liberia',en:'Liberia'},
  {code:'LY',de:'Libyen',en:'Libya'},
  {code:'LT',de:'Litauen',en:'Lithuania'},
  {code:'MG',de:'Madagaskar',en:'Madagascar'},
  {code:'MW',de:'Malawi',en:'Malawi'},
  {code:'MY',de:'Malaysia',en:'Malaysia'},
  {code:'MV',de:'Malediven',en:'Maldives'},
  {code:'ML',de:'Mali',en:'Mali'},
  {code:'MT',de:'Malta',en:'Malta'},
  {code:'MA',de:'Marokko',en:'Morocco'},
  {code:'MR',de:'Mauretanien',en:'Mauritania'},
  {code:'MU',de:'Mauritius',en:'Mauritius'},
  {code:'MX',de:'Mexiko',en:'Mexico'},
  {code:'MD',de:'Moldau',en:'Moldova'},
  {code:'MC',de:'Monaco',en:'Monaco'},
  {code:'MN',de:'Mongolei',en:'Mongolia'},
  {code:'ME',de:'Montenegro',en:'Montenegro'},
  {code:'MZ',de:'Mosambik',en:'Mozambique'},
  {code:'MM',de:'Myanmar',en:'Myanmar'},
  {code:'NA',de:'Namibia',en:'Namibia'},
  {code:'NR',de:'Nauru',en:'Nauru'},
  {code:'NP',de:'Nepal',en:'Nepal'},
  {code:'NZ',de:'Neuseeland',en:'New Zealand'},
  {code:'NI',de:'Nicaragua',en:'Nicaragua'},
  {code:'NL',de:'Niederlande',en:'Netherlands'},
  {code:'NE',de:'Niger',en:'Niger'},
  {code:'NG',de:'Nigeria',en:'Nigeria'},
  {code:'MK',de:'Nordmazedonien',en:'North Macedonia'},
  {code:'NO',de:'Norwegen',en:'Norway'},
  {code:'OM',de:'Oman',en:'Oman'},
  {code:'PK',de:'Pakistan',en:'Pakistan'},
  {code:'PW',de:'Palau',en:'Palau'},
  {code:'PA',de:'Panama',en:'Panama'},
  {code:'PG',de:'Papua-Neuguinea',en:'Papua New Guinea'},
  {code:'PY',de:'Paraguay',en:'Paraguay'},
  {code:'PE',de:'Peru',en:'Peru'},
  {code:'PH',de:'Philippinen',en:'Philippines'},
  {code:'PL',de:'Polen',en:'Poland'},
  {code:'PT',de:'Portugal',en:'Portugal'},
  {code:'RW',de:'Ruanda',en:'Rwanda'},
  {code:'RO',de:'Rumänien',en:'Romania'},
  {code:'RU',de:'Russland',en:'Russia'},
  {code:'SB',de:'Salomonen',en:'Solomon Islands'},
  {code:'ZM',de:'Sambia',en:'Zambia'},
  {code:'WS',de:'Samoa',en:'Samoa'},
  {code:'SM',de:'San Marino',en:'San Marino'},
  {code:'ST',de:'São Tomé und Príncipe',en:'São Tomé and Príncipe'},
  {code:'SA',de:'Saudi-Arabien',en:'Saudi Arabia'},
  {code:'SE',de:'Schweden',en:'Sweden'},
  {code:'SN',de:'Senegal',en:'Senegal'},
  {code:'RS',de:'Serbien',en:'Serbia'},
  {code:'SC',de:'Seychellen',en:'Seychelles'},
  {code:'SL',de:'Sierra Leone',en:'Sierra Leone'},
  {code:'ZW',de:'Simbabwe',en:'Zimbabwe'},
  {code:'SG',de:'Singapur',en:'Singapore'},
  {code:'SK',de:'Slowakei',en:'Slovakia'},
  {code:'SI',de:'Slowenien',en:'Slovenia'},
  {code:'SO',de:'Somalia',en:'Somalia'},
  {code:'ES',de:'Spanien',en:'Spain'},
  {code:'LK',de:'Sri Lanka',en:'Sri Lanka'},
  {code:'KN',de:'St. Kitts und Nevis',en:'Saint Kitts and Nevis'},
  {code:'LC',de:'St. Lucia',en:'Saint Lucia'},
  {code:'VC',de:'St. Vincent und die Grenadinen',en:'Saint Vincent and the Grenadines'},
  {code:'ZA',de:'Südafrika',en:'South Africa'},
  {code:'SD',de:'Sudan',en:'Sudan'},
  {code:'SS',de:'Südsudan',en:'South Sudan'},
  {code:'SR',de:'Suriname',en:'Suriname'},
  {code:'SY',de:'Syrien',en:'Syria'},
  {code:'TJ',de:'Tadschikistan',en:'Tajikistan'},
  {code:'TZ',de:'Tansania',en:'Tanzania'},
  {code:'TH',de:'Thailand',en:'Thailand'},
  {code:'TL',de:'Timor-Leste',en:'Timor-Leste'},
  {code:'TG',de:'Togo',en:'Togo'},
  {code:'TO',de:'Tonga',en:'Tonga'},
  {code:'TT',de:'Trinidad und Tobago',en:'Trinidad and Tobago'},
  {code:'TD',de:'Tschad',en:'Chad'},
  {code:'CZ',de:'Tschechien',en:'Czech Republic'},
  {code:'TN',de:'Tunesien',en:'Tunisia'},
  {code:'TR',de:'Türkei',en:'Turkey'},
  {code:'TM',de:'Turkmenistan',en:'Turkmenistan'},
  {code:'TV',de:'Tuvalu',en:'Tuvalu'},
  {code:'UG',de:'Uganda',en:'Uganda'},
  {code:'UA',de:'Ukraine',en:'Ukraine'},
  {code:'HU',de:'Ungarn',en:'Hungary'},
  {code:'UY',de:'Uruguay',en:'Uruguay'},
  {code:'UZ',de:'Usbekistan',en:'Uzbekistan'},
  {code:'VU',de:'Vanuatu',en:'Vanuatu'},
  {code:'VE',de:'Venezuela',en:'Venezuela'},
  {code:'AE',de:'Vereinigte Arabische Emirate',en:'United Arab Emirates'},
  {code:'US',de:'Vereinigte Staaten',en:'United States'},
  {code:'GB',de:'Vereinigtes Königreich',en:'United Kingdom'},
  {code:'VN',de:'Vietnam',en:'Vietnam'},
  {code:'CF',de:'Zentralafrikanische Republik',en:'Central African Republic'},
  {code:'CY',de:'Zypern',en:'Cyprus'},
];
