function closeModal(id){document.getElementById(id).classList.remove('open');}
function openDocModal(editId){
  const L=typeof _LANG!=='undefined'?_LANG:'de';
  S.editDocId=editId||null;document.getElementById('docModalTitle').textContent=editId?(L==='en'?'Edit':'Bearbeiten'):(L==='en'?'Add':'Hinzufügen');
  document.getElementById('docForm').innerHTML=`<div class="fg fg-full"><label>Name</label><input id="df_n"></div><div class="fg"><label>${L==='en'?'Category':'Kategorie'}</label><select id="df_c">${CATS.map(c=>`<option>${c}</option>`).join('')}</select></div><div class="fg"><label>${L==='en'?'Expiry Date':'Ablaufdatum'}</label><input type="date" id="df_e"></div><div class="fg"><label>Version</label><input id="df_v"></div><div class="fg"><label>${L==='en'?'Responsible':'Verantwortlich'}</label><input id="df_o"></div><div class="fg fg-full"><label>${L==='en'?'Standards':'Normen'}</label><div class="norm-chips" id="df_norms">${Object.entries(NORMS).map(([k,v])=>`<div class="nc ${v.m==='qm'?'qc':v.m==='itgov'?'ic':''}" data-norm="${k}" onclick="this.classList.toggle('active')" style="font-size:.65rem;padding:3px 8px">${k}</div>`).join('')}</div></div><div class="fg fg-full"><label>${L==='en'?'Check Points':'Prüfpunkte'}</label><select id="df_cp" multiple style="min-height:60px"><option value="">${L==='en'?'None':'Keine'}</option>${allCPs().map(cp=>`<option value="${cp.id}">${cp.sec} → ${cp.l}</option>`).join('')}</select></div><div class="fg fg-full"><label>${L==='en'?'Notes':'Notizen'}</label><textarea id="df_nt" rows="2"></textarea></div>`;
  if(editId){const d=S.docs.find(x=>x.id===editId);if(d){document.getElementById('df_n').value=d.name||'';document.getElementById('df_c').value=d.category;document.getElementById('df_e').value=d.expiry||'';document.getElementById('df_v').value=d.version||'';document.getElementById('df_o').value=d.owner||'';document.getElementById('df_nt').value=d.notes||'';(d.norms||[]).forEach(n=>{const c=document.querySelector(`#df_norms [data-norm="${n}"]`);if(c)c.classList.add('active');});(d.checkpoints||[]).forEach(cp=>{const o=document.querySelector(`#df_cp option[value="${cp}"]`);if(o)o.selected=true;});}}
  document.getElementById('docModal').classList.add('open');
}
function saveDoc(){const L=typeof _LANG!=='undefined'?_LANG:'de';const name=document.getElementById('df_n').value.trim();if(!name){toast(L==='en'?'Please enter a name':'Bitte einen Namen eingeben','error');return;}const obj={name,category:document.getElementById('df_c').value,expiry:document.getElementById('df_e').value,version:document.getElementById('df_v').value.trim(),owner:document.getElementById('df_o').value.trim(),notes:document.getElementById('df_nt').value.trim(),norms:[...document.querySelectorAll('#df_norms .nc.active')].map(e=>e.dataset.norm),checkpoints:[...document.getElementById('df_cp').selectedOptions].map(o=>o.value).filter(v=>v)};if(S.editDocId){const d=S.docs.find(x=>x.id===S.editDocId);if(d)Object.assign(d,obj);toast(L==='en'?'Document updated':'Dokument aktualisiert','success');}else{S.docs.push({id:Date.now(),...obj,addedAt:new Date().toISOString()});toast(L==='en'?'Document added':'Dokument hinzugefügt','success');}save();closeModal('docModal');render();}

function openMaModal(editId){
  const L=typeof _LANG!=='undefined'?_LANG:'de';
  S.editMaId=editId||null;document.getElementById('maModalTitle').textContent=editId?(L==='en'?'Edit':'Bearbeiten'):(L==='en'?'New Measure':'Neue Maßnahme');
  document.getElementById('maForm').innerHTML=`<div class="fg fg-full"><label>${L==='en'?'Title':'Titel'}</label><input id="ma_t"></div><div class="fg"><label>${L==='en'?'Priority':'Priorität'}</label><select id="ma_p"><option>Kritisch</option><option>Hoch</option><option>Mittel</option><option>Niedrig</option></select></div><div class="fg"><label>Status</label><select id="ma_s"><option>offen</option><option>in Bearbeitung</option><option>erledigt</option></select></div><div class="fg"><label>${L==='en'?'Responsible':'Verantwortlich'}</label><input id="ma_o"></div><div class="fg"><label>${L==='en'?'Deadline':'Frist'}</label><input type="date" id="ma_d"></div><div class="fg fg-full"><label>${L==='en'?'Description':'Beschreibung'}</label><textarea id="ma_desc" rows="2"></textarea></div>`;
  if(editId){const m=S.massnahmen.find(x=>x.id===editId);if(m){document.getElementById('ma_t').value=m.title;document.getElementById('ma_p').value=m.prio;document.getElementById('ma_s').value=m.status;document.getElementById('ma_o').value=m.owner||'';document.getElementById('ma_d').value=m.deadline||'';document.getElementById('ma_desc').value=m.desc||'';}}
  document.getElementById('maModal').classList.add('open');
}
function saveMa(){const L=typeof _LANG!=='undefined'?_LANG:'de';const t=document.getElementById('ma_t').value.trim();if(!t){toast(L==='en'?'Please enter a title':'Bitte einen Titel eingeben','error');return;}const obj={title:t,prio:document.getElementById('ma_p').value,status:document.getElementById('ma_s').value,owner:document.getElementById('ma_o').value.trim(),deadline:document.getElementById('ma_d').value,desc:document.getElementById('ma_desc').value.trim()};if(S.editMaId){const m=S.massnahmen.find(x=>x.id===S.editMaId);if(m)Object.assign(m,obj);toast(L==='en'?'Measure updated':'Maßnahme aktualisiert','success');}else{S.massnahmen.push({id:Date.now(),...obj});toast(L==='en'?'Measure created':'Maßnahme erstellt','success');}save();closeModal('maModal');render();}

function showEsk(){const L=typeof _LANG!=='undefined'?_LANG:'de';const krit=[];activeChecks().forEach(ch=>ch.items.forEach(it=>{if(S.findings[it.id]?.status==='kritisch')krit.push({l:it.l,sec:ch.l,note:S.findings[it.id]?.note||''});}));
document.getElementById('eskText').value=L==='en'
?`URGENT – Escalation of Critical Deficiencies\n\nDear Management,\n\nduring the inspection on ${S.meta.datum||'[Date]'} at "${S.meta.objekt||'[Object]'}", ${krit.length} critical deficiencies were identified:\n\n${krit.map((k,i)=>`${i+1}. ${k.sec} → ${k.l}${k.note?' ('+k.note+')':''}`).join('\n')}\n\nImmediate corrective measures required pursuant to NIS2 §38 / ISO 31000.\n\nKind regards,\n${S.meta.pruefer||'[Auditor]'}\nSecureStay Solutions UG (limited liability)`
:`DRINGEND – Eskalation kritischer Mängel\n\nSehr geehrte Geschäftsleitung,\n\nbei der Begehung am ${S.meta.datum||'[Datum]'} des Objekts "${S.meta.objekt||'[Objekt]'}" wurden ${krit.length} kritische Mängel festgestellt:\n\n${krit.map((k,i)=>`${i+1}. ${k.sec} → ${k.l}${k.note?' ('+k.note+')':''}`).join('\n')}\n\nSofortige Korrekturmaßnahmen gemäß NIS2 §38 / ISO 31000 erforderlich.\n\nMit freundlichen Grüßen,\n${S.meta.pruefer||'[Auditor]'}\nSecureStay Solutions UG (haftungsbeschränkt)`;
document.getElementById('eskModal').classList.add('open');}
